---
title: "Homework 1"
author: "Caitlin Jeffrey"
date: "January 23, 2019"
output: html_document
---

#Exercise 1

---

Googled **R package reshape** and downloaded PDF to R_manual folder

---

Installed **reshape**

install.packages("reshape", dependencies = T)
Installing package into 'C:/Users/caitl/OneDrive/Documents/R/win-library/3.5'
(as 'lib' is unspecified)
also installing the dependency 'plyr'

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/plyr_1.8.4.zip'
Content type 'application/zip' length 1298190 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/reshape_0.8.8.zip'
Content type 'application/zip' length 168496 bytes (164 KB)
downloaded 164 KB

package 'plyr' successfully unpacked and MD5 sums checked
package 'reshape' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\caitl\AppData\Local\Temp\RtmpIjhLPH\downloaded_packages
        
---

Determined active packages in current R session

search()
[1] ".GlobalEnv"        "package:stats"     "package:graphics" 
[4] "package:grDevices" "package:utils"     "package:datasets" 
[7] "package:methods"   "Autoloads"         "package:base"  

---

Loaded reshape into R session and documented packages in my R session 

library("reshape")
search()
 [1] ".GlobalEnv"        "package:reshape"   "package:stats"    
 [4] "package:graphics"  "package:grDevices" "package:utils"    
 [7] "package:datasets"  "package:methods"   "Autoloads" 
 
 ---
 
 Unloaded reshape, then checked to see it was gone from active packages
 
detach("package:reshape", unload=TRUE)

search()
[1] ".GlobalEnv"        "package:stats"     "package:graphics" 
[4] "package:grDevices" "package:utils"     "package:datasets" 
[7] "package:methods"   "Autoloads"         "package:base"  

---

Updated existing packages

update.packages(ask = F)
Warning in install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  'lib = "C:/Program Files/R/R-3.5.2/library"' is not writable
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/class_7.3-15.zip'
Content type 'application/zip' length 106126 bytes (103 KB)
downloaded 103 KB

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/codetools_0.2-16.zip'
Content type 'application/zip' length 89080 bytes (86 KB)
downloaded 86 KB

package 'class' successfully unpacked and MD5 sums checked
package 'codetools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\caitl\AppData\Local\Temp\RtmpIjhLPH\downloaded_packages
        
---

  
  